### ISSUE TITLE
Edit and release of Hack Princeton videos, trial with fiverr

### ISSUE THREAD

**Issue by atsigndenise** [atsign-company/events#54]

**Comment by hakeemawbrey** [comment]
We were asked to blurr out any students in our 2 videos from Hack princeton - This is a very timely process for 1hr + videos..

We can outsource for $15-$25 per video on Fiver with their marketplace. https://www.fiverr.com/s_wasay_ali/blur-peoples-faces-products-or-anything-in-the-video?utm_campaign=base_gig_show_share&utm_content=&utm_medium=shared&utm_source=mobile&utm_term=

I've used fiverr before for the company. This wouldn't be a trial since fiver is a market place and every new project/outsourcing can be a different person based on the project.

**Comment by ksanty** [comment]
@hakeemawbrey [here is the one](https://www.fiverr.com/graphicsify/create-a-fresh-and-professional-app-promo-video-or-explainer-video) @rtilney recommended

**Comment by hakeemawbrey** [comment]
@ksanty This is a little different, we were asked to blur out students that appeared in our hack princeton videos
- CEO & CTO Pannel
- Tyler and Xaviers code session

Most of the appearances in the two videos that are students are from the hosts. We are clarifying with the hack princeton team who all needs to be blurred out in more details.

**Comment by atsigndenise** [comment]
Hakeem posted video, closing this issue
